GET http://localhost:3001/tickets

###

GET http://localhost:3001/tickets/0b1efcc3-3ffe-4d5e-9da6-7da55c42856a

###

POST http://localhost:3001/tickets
Content-Type: application/json

{
  "price":100.0,
  "content":"entrada para festa do admin!",
  "eventId":"af3f0c1d-e484-429d-86f5-7c1edcadae05",
  "ticketOwnerId":"0b1efcc3-3ffe-4d5e-9da6-7da55c42856a"
    //ticket ID 3e540004-dd2b-43cc-a64a-611a303c9958

}

###

PUT http://localhost:3001/tickets/2
Content-Type: application/json

{
  "name": "Updated Luw",
  "email":"ld97@gmail.com"
}

###

DELETE http://localhost:3001/tickets/2
